#! /bin/bash

. $(dirname $(readlink -f $0))/mh-settings


export EMBED=0
export USE_SYSTEM_LIB=1

# -- their stuff
pyfpm --iteration 0 py
pyfpm --iteration 0 apipkg
pyfpm --iteration 0 sqlite3dbm
pyfpm --iteration 0 odfpy
pyfpm --iteration 0 -d libfribidi0 pyfribidi

# -- our stuff

pyfpm --iteration 0 timelib
pyfpm --iteration 0 -d python-greenlet -d python-gevent qserve
pyfpm --iteration 5 -d python-imaging -d python-roman -d python-gevent -d python-odfpy mwlib
pyfpm --iteration 0 mwlib.ext
pyfpm --iteration 0 mwlib.rl
pyfpm --iteration 0 pyzim
pyfpm --iteration 0 mwlib.zim
pyfpm --iteration 0 -d libev4 -d libc-ares2 gevent

# EMBED=1 pyfpm --iteration 0 --replaces python-gevent --provides python-gevent -n python-static-gevent gevent
