#! /bin/sh

: ${MH_ROOT:=~/mh-root}
: ${MH_ARCHIVE:=${MH_ROOT}/archive}
: ${MH_BUILD:=${MH_ROOT}/tmp}

: ${MH_INDEX_URL:=${PIP_INDEX_URL:-http://pypi.pediapress.com/simple}}

: ${MH_PYTHON:=/usr/bin/python}
: ${MH_EASY_INSTALL:=/usr/bin/easy_install}
